# Generated by Django 2.1.4 on 2019-02-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddComp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comp_ID', models.CharField(max_length=1000)),
                ('Admin_ID', models.CharField(max_length=1000)),
                ('Comp_Name', models.CharField(max_length=1000)),
                ('Cate_Name', models.CharField(max_length=1000)),
                ('About', models.CharField(max_length=2000)),
                ('Status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'AddComp',
            },
        ),
        migrations.CreateModel(
            name='CanData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Can_ID', models.CharField(max_length=1000)),
                ('Candidate_Name', models.CharField(max_length=1000)),
                ('Candidate_Email', models.CharField(max_length=1000)),
                ('Comp_ID', models.CharField(max_length=1000)),
                ('Course', models.CharField(max_length=200)),
                ('Branch', models.CharField(max_length=200)),
                ('Institution_Name', models.CharField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='CompQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_ID', models.CharField(max_length=15)),
                ('Comp_ID', models.CharField(max_length=1000)),
                ('Ques_No', models.CharField(max_length=1000)),
                ('Ques', models.CharField(max_length=10000)),
                ('A', models.CharField(max_length=2000)),
                ('B', models.CharField(max_length=2000)),
                ('C', models.CharField(max_length=2000)),
                ('D', models.CharField(max_length=2000)),
                ('Answer', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'CompQuiz',
            },
        ),
        migrations.CreateModel(
            name='NewAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institution_Name', models.CharField(max_length=1000)),
                ('Admin_Name', models.CharField(max_length=100)),
                ('Admin_Post', models.CharField(max_length=100)),
                ('Mobile', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'NewAdmin',
            },
        ),
    ]
