# Generated by Django 2.1.4 on 2019-02-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_ques'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ques',
        ),
        migrations.AddField(
            model_name='candata',
            name='Login_ID',
            field=models.CharField(default=123456, max_length=1000),
            preserve_default=False,
        ),
    ]
