# Generated by Django 2.1.4 on 2019-03-01 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190228_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcomp',
            old_name='About',
            new_name='About_Comp',
        ),
    ]
