# Generated by Django 2.0.2 on 2019-03-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_newadmin_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcomp',
            name='Time',
            field=models.IntegerField(default=40),
            preserve_default=False,
        ),
    ]
